# Generated by Django 4.0.4 on 2022-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='number_of_goals_diffrence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
