# Generated by Django 4.0.4 on 2022-06-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0002_team_game_played_team_number_of_goals_diffrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='card',
            field=models.CharField(choices=[('--', '------'), ('YE', 'Yellow'), ('RE', 'Red')], default='', max_length=10),
        ),
    ]
