# Generated by Django 4.0.3 on 2022-04-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0003_remove_zawodnik_druzyna_druzyna_stadion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.TextField(max_length=10)),
                ('narodowosc', models.TextField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Zawodnik',
                'verbose_name_plural': 'Zawodnicy',
            },
        ),
        migrations.RemoveField(
            model_name='druzyna',
            name='zawodnik',
        ),
        migrations.DeleteModel(
            name='Zawodnik',
        ),
        migrations.AddField(
            model_name='druzyna',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GamePLAY.player'),
        ),
    ]
