# Generated by Django 4.0.3 on 2022-04-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0004_player_remove_druzyna_zawodnik_delete_zawodnik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druzyna',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='GamePLAY.player'),
        ),
    ]
