# Generated by Django 4.0.3 on 2022-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0005_alter_druzyna_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='data_urodzenia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ilosc_bramek',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pozycja',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='imie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='narodowosc',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nazwisko',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Druzyna',
        ),
    ]
