# Generated by Django 4.0.3 on 2022-04-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0006_player_data_urodzenia_player_ilosc_bramek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pozycja',
            field=models.CharField(choices=[('BR', 'Bramkarz'), ('Ob', 'Obrońca'), ('Po', 'Pomocnik'), ('Na', 'Napastnik')], max_length=10, null=True),
        ),
    ]
