# Generated by Django 4.0.3 on 2022-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0008_remove_player_narodowosc_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nazwisko',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
