# Generated by Django 4.0.3 on 2022-04-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0010_druzyna_player_druzyna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ilosc_bramek',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_meczu', models.DateField(null=True)),
                ('nr_kolejki', models.IntegerField(null=True)),
                ('wynik_meczu', models.CharField(max_length=5, null=True)),
                ('druzynaGosci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goscie', to='GamePLAY.druzyna')),
                ('druzynaGospodarzy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gospodarze', to='GamePLAY.druzyna')),
            ],
        ),
    ]
