# Generated by Django 4.0.3 on 2022-04-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0011_alter_player_ilosc_bramek_mecz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mecz',
            options={'verbose_name': 'Mecz', 'verbose_name_plural': 'Mecze'},
        ),
    ]
