# Generated by Django 4.0.3 on 2022-04-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0015_alter_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_score',
            field=models.CharField(blank=True, default='-', max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Defender'), ('CM', 'Midfielder'), ('ST', 'Striker')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=50)),
                ('team1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='GamePLAY.team')),
                ('team2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='GamePLAY.team')),
                ('team3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='GamePLAY.team')),
                ('team4', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team4', to='GamePLAY.team')),
                ('team5', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team5', to='GamePLAY.team')),
                ('team6', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team6', to='GamePLAY.team')),
                ('team7', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team7', to='GamePLAY.team')),
                ('team8', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team8', to='GamePLAY.team')),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
    ]
