# Generated by Django 4.0.4 on 2022-04-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0016_alter_match_match_date_alter_match_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_goals', models.IntegerField(default=0)),
                ('number_of_assists', models.IntegerField(default=0)),
                ('number_of_passes', models.IntegerField(default=0)),
                ('number_of_fouls', models.IntegerField(default=0)),
                ('match', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='GamePLAY.match')),
                ('player_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='player_name', to='GamePLAY.player')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
