# Generated by Django 4.0.4 on 2022-04-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0017_team_points_statistic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistic',
            new_name='StatisticOfPlayer',
        ),
        migrations.AlterModelOptions(
            name='statisticofplayer',
            options={'verbose_name': 'StatisticOfPlayer', 'verbose_name_plural': 'StatisticsOfPlayer'},
        ),
    ]
