# Generated by Django 4.0.4 on 2022-04-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0019_alter_match_queue_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatisticOfPlayer',
            new_name='PlayerStatistic',
        ),
        migrations.AlterModelOptions(
            name='playerstatistic',
            options={'verbose_name': 'PlayerStatistic', 'verbose_name_plural': 'PlayerStatistics'},
        ),
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team_name_in_TeamStatistic', to='GamePLAY.team')),
            ],
            options={
                'verbose_name': 'TeamStatistic',
                'verbose_name_plural': 'TeamStatistics',
            },
        ),
    ]
