# Generated by Django 4.0.4 on 2022-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0021_remove_league_team1_remove_league_team2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_backgroud_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
