# Generated by Django 4.0.4 on 2022-05-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0022_staticitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticitems',
            old_name='main_backgroud_image',
            new_name='main_background_image',
        ),
    ]
