# Generated by Django 4.0.4 on 2022-05-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0023_rename_main_backgroud_image_staticitems_main_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticitems',
            options={'verbose_name': 'StaticItem', 'verbose_name_plural': 'StaticItems'},
        ),
    ]
