# Generated by Django 4.0.4 on 2022-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0025_alter_staticitems_main_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticitems',
            name='main_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
