# Generated by Django 4.0.4 on 2022-05-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0026_alter_staticitems_main_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='team_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team_namee', to='GamePLAY.team'),
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='number_of_fouls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='number_of_goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstatistic',
            name='number_of_passes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
