# Generated by Django 4.0.4 on 2022-05-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0027_playerstatistic_team_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number_of_goals',
        ),
    ]
