# Generated by Django 4.0.4 on 2022-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0028_remove_player_number_of_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
