# Generated by Django 4.0.4 on 2022-05-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0029_alter_playerstatistic_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstatistic',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playerstatistic',
            name='team_name',
        ),
    ]
