# Generated by Django 4.0.4 on 2022-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0030_remove_playerstatistic_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number_of_goals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
