# Generated by Django 4.0.4 on 2022-05-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0033_alter_match_away_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
