# Generated by Django 4.0.4 on 2022-05-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0034_playerstatistic_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistic',
            name='away_team',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='home_team',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
