# Generated by Django 4.0.4 on 2022-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0035_playerstatistic_away_team_playerstatistic_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticitems',
            name='contact_us_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
