# Generated by Django 4.0.4 on 2022-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0037_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
        migrations.AlterField(
            model_name='search',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
