# Generated by Django 4.0.4 on 2022-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0040_alter_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, default='<jamming-date>', null=True),
        ),
    ]
