# Generated by Django 4.0.4 on 2022-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0042_alter_player_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
