# Generated by Django 4.0.4 on 2022-05-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0043_alter_player_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
    ]
