# Generated by Django 4.0.4 on 2022-05-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0045_alter_player_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstatistic',
            name='player_name',
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='player', to='GamePLAY.player'),
        ),
    ]
