# Generated by Django 4.0.4 on 2022-05-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0046_remove_playerstatistic_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='playerr', to='GamePLAY.player'),
        ),
    ]
