# Generated by Django 4.0.4 on 2022-05-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePLAY', '0047_alter_playerstatistic_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistic',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GamePLAY.player'),
        ),
    ]
